### ISSUE TITLE
missing install.php in docker image breaks startup with empty database

### ISSUE THREAD

**Issue by fun3md** [OCSInventory-NG/OCSInventory-Docker-Image#12]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Docker host's operating system : Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64
Mysql Server version : mariaDB 10.3.11

### Docker informations
Docker compose version : v3
Docker version : 18.03.1-ce

### Problem's description
When starting "ocsinventory/ocsinventory-docker-image:latest" against a empty database on a working mysql host the application just throws a "HTTP 500 error" and a cryptic log entry in apache2/error.log that "install.php" is required.
After connecting in the container and doing a "wget https://raw.githubusercontent.com/OCSInventory-NG/OCSInventory-ocsreports/master/install.php" in "/usr/share/ocsinventory-reports/ocsreports/" the install procedure started.

Please add either a helpful message or remove the "rm ... install.php" from the docker file.

Thanks ...

**Comment by jackadam1981** [comment]
It realy help me.
I've been stuck here for a long time.

**Comment by MyTheValentinus** [comment]
Hello,
To fix issue i will pass a environment variable "INSIDE_DOCKER" and remove this check if variable is true from php main code of OCS Inventory.
Stay tuned !

Thanks

**Comment by h4wkmoon** [comment]
Any updates ?

**Comment by Edzilla2000** [comment]
Hi, this problem is still happening with the current docker image, any ETA?

**Comment by gillesdubois** [comment]
Hi,

Sorry with the delay we went trough a complete rework of our image.
2.6 / nightly / dev tags are now available.

A complete documentation is available on our wiki.
Compose files are now located on the image repository and not on this one anymore.

Regards,
Gilles Dubois.
