### ISSUE TITLE
 How to set the time zone?

### ISSUE THREAD

**Issue by jackadam1981** [OCSInventory-NG/OCSInventory-Docker-Image#14]
How to set the time zone?

**Comment by gillesdubois** [comment]
Hi,

Sorry with the delay we went trough a complete rework of our image.
2.6 / nightly / dev tags are now available.

A complete documentation is available on our wiki. (Timezone explanation are also there)
Compose files are now located on the image repository and not on this one anymore.

Regards,
Gilles Dubois.
