### ISSUE TITLE
Build OCS 2.6 Docker Image

### ISSUE THREAD

**Issue by sebaplaza** [OCSInventory-NG/OCSInventory-Docker-Image#18]
Hello,

I see that the last build of docker image still uses OCS Server 2.5

Can you generate a 2.6 image ?

Thanks

**Comment by space4u** [comment]
Hello,
+1
please update the Docker Image to 2.6.

regards

**Comment by space4u** [comment]
Hello,
please add in new docker images php7.0-ldap!

thanks and regards

**Comment by jerome-lemaire** [comment]
I made my own 2.6 image if you want :
https://hub.docker.com/r/jeromelemaire/ocsinventory-docker-image

**Comment by sebaplaza** [comment]
why nobody is watching this ?

2.6 was released on 18 May 2019 !

![image](https://user-images.githubusercontent.com/6557434/70431815-1fcdbd80-1a7e-11ea-9b88-5a3c0e9cbf7d.png)

**Comment by gillesdubois** [comment]
Hi,

Sorry with the delay we went trough a complete rework of our image.
2.6 / nightly / dev tags are now available.

A complete documentation is available on our wiki.
Compose files are now located on the image repository and not on this one anymore.

Regards,
Gilles Dubois.
