### ISSUE TITLE
install.php missing from latest docker image on docker hub

### ISSUE THREAD

**Issue by thelamer** [OCSInventory-NG/OCSInventory-Docker-Image#2]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Docker host's operating system : Debian Jessie
Mysql Server version : NA the server never attempts to connect to the DB

### Docker informations
Docker compose version :Docker version 17.03.1-ce, build c6d412e
Docker version : Docker version 17.03.1-ce, build c6d412e

### Problem's description
The latest tag seems broken at head on a new spinup, this should be relatively easy to reproduce here is the SHA from dockerhub: 
sha256:416190c759c3d6195f2c26da46a7843ca2fbeff27dbe7a7548c0218764e05e51

When you start the container and access ocsreports path you get a 500 back, the actual error is: 
`[Thu Aug 17 02:59:13.857335 2017] [:error] [pid 14] [client 172.16.53.91:10376] PHP Warning:  require(install.php): failed to open stream: No such file or directory in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 167
[Thu Aug 17 02:59:13.857428 2017] [:error] [pid 14] [client 172.16.53.91:10376] PHP Fatal error:  require(): Failed opening required 'install.php' (include_path='.:/usr/share/php:/usr/share/pear') in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 167
`

**Comment by exander77** [comment]
Confirming, had to manually download into a running instance.

**Comment by CondormanFr** [comment]
I'm in the same case. But I didn't undestand what I have to do. Where is this install.php ? Thanks

**Comment by MyTheValentinus** [comment]
Hello,
Not able to reproduce in latest version.
Thanks
