### ISSUE TITLE
Rest API

### ISSUE THREAD

**Issue by h4wkmoon** [OCSInventory-NG/OCSInventory-Docker-Image#21]
Hi, it seems that the reast api is not activated in the 2.5 docker image.

could you please add it ?

**Comment by gillesdubois** [comment]
Hi,

Sorry with the delay we went trough a complete rework of our image.
2.6 / nightly / dev tags are now available.

A complete documentation is available on our wiki.
Compose files are now located on the image repository and not on this one anymore.

REST API is still not supported but we are gonna make it soon.

Regards,
Gilles Dubois.
