### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by skycrash** [OCSInventory-NG/OCSInventory-Docker-Image#22]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Docker host's operating system : CentOS Linux release 7.5.1804 (Core)
Mysql Server version : mysql  Ver 15.1 Distrib 5.5.60-MariaDB, for Linux (x86_64) using readline 5.1

### Docker informations
Docker compose version :docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
Docker version : Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64
 Experimental:    false

### Problem's description
I can't install plugins, i put the file in "/usr/share/ocsinventory-reports/ocsreports/plugins/" 
unzip plugin, but in the web interface, dont show me to enable or install

**Comment by gillesdubois** [comment]
Hi,

Our Docker image has been reworked completly.
2.6 / nightly / dev tags are now available.

A complete documentation is available on wiki.
Compose files are now located on the image repository and not on this one anymore.

Extension engine has been rework since it suffered from a bug in the earliers versions.

Regards,
Gilles Dubois.
