### ISSUE TITLE
Extensions and python-scp

### ISSUE THREAD

**Issue by thefathacker** [OCSInventory-NG/OCSInventory-Docker-Image#24]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Docker host's operating system : Ubuntu 18.04.3 LTS Server
Mysql Server version : 5.7

### Docker informations
Docker compose version :
Docker version : 19.03.5, build 633a0ea838

### Problem's description
Hi OCS

The python scp in not installed as a result I am unable to using tools/install_plugin.py

Also adding a file to extensions/ does not result in the web client listing the file as available to install

Regards,

The Fat Hacker

**Comment by gillesdubois** [comment]
Hi,

It working on my dev container, are you copying the .zip file ? You need to cp the content of the zip and not the zip itself.

Regards,
Gilles Dubois.

**Comment by thefathacker** [comment]
Hi @gillesdubois,

Thank you, The documentation is was not clear on the plugin install.

As for scp, I am looking forward to being able to use plugins.

Regards,
@thefathacker

**Comment by gillesdubois** [comment]
Hi @thefathacker ,

Our documentation has been updated : 
http://wiki.ocsinventory-ng.org/10.Plugin-engine/Using-plugins-installer/

Regards,
Gilles Dubois.
