### ISSUE TITLE
Missing files at container restart

### ISSUE THREAD

**Issue by space4u** [OCSInventory-NG/OCSInventory-Docker-Image#25]
### General informations
Docker host's operating system : Ubuntu Server 18.04.3 LTS
Mysql Server version : 5.7.29

### Docker informations
Docker compose version : 1.17.1
Docker version : 19.03.5

### Problem's description
After restart the ocsinventory-server Container the config files are missing to copy.
I see the followig error in the docker log:

cp: cannot stat '/tmp/ocsinventory-server.conf': No such file or directory
cp: cannot stat '/tmp/ocsinventory-reports.conf': No such file or directory
cp: cannot stat '/tmp/dbconfig.inc.php': No such file or directory

The login on the ocsreports website is not possible, her I get the following errors:

ERROR: MySql connection problem 2002
No such file or directory
ERROR: MySql connection problem 2002
No such file or directory

**Try Workaroud but FAILED:**
I have try to create the missing directory /tmp and missing config file.
After restart the ocsinventory-server Container the config files are automatically deleted :(

Thanks and only the best :)

**Comment by gillesdubois** [comment]
Hi,

Thx for your report, indeed there is a problem, will fix this asap.

Regards,
Gilles Dubois.

**Comment by thefathacker** [comment]
Hi @gillesdubois and @space4u,

While I did notice this issue using 2.6/latest. I have not had this issue with dev

Regards

**Comment by mgonza02** [comment]
Hello dears
After several attempts I have with different tags, the same problem
...
Installing /usr/local/share/perl5/Apache/Ocsinventory/Plugins/Apache.pm
Installing /usr/local/share/perl5/Apache/Ocsinventory/Plugins/Modules.pm
Appending installation info to /usr/lib64/perl5/perllocal.pod
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.9. Set the 'ServerName' directive globally to suppress this message
Hope someone can help me

**Comment by sjthespian** [comment]
I am seeing the same thing here after the last update. Is there a workaround in the meantime?
