### ISSUE TITLE
Container restart Loop "httpd (pid 156) already running

### ISSUE THREAD

**Issue by space4u** [OCSInventory-NG/OCSInventory-Docker-Image#27]
### General informations
Docker host's operating system : Ubuntu Server 18.04.4 LTS
Mysql Server version : MySQL 5.7

### Docker informations
Docker compose version : 1.17.1
Docker version : 19.03.6

### Problem's description
After some restarts of the ocs-inventoy, the container is hanging in a boot loop.
The last line of the conatiner log is "httpd (pid 156) already running" and
the command docker ps shows "Restarting (0) 3 seconds ago".

**Comment by gillesdubois** [comment]
Hi @space4u ,

Which tag are you using ?

Regards,
Gilles Dubois.

**Comment by space4u** [comment]
> Hi @space4u ,
> 
> Which tag are you using ?
> 
> Regards,
> Gilles Dubois.

Hi @gillesdubois,
sorry, i use the **latest** tag. The OCS show me the 2.6 version.

Regards

**Comment by gillesdubois** [comment]
Hi,

I can't reproduce the bug. Does it happen everytime ?

Regards,
Gilles Dubois.
