### ISSUE TITLE
Mounting volumes over existing data

### ISSUE THREAD

**Issue by N3RG4L** [OCSInventory-NG/OCSInventory-Docker-Image#3]
### General informations
Docker host's operating system : Amazon 4.9.32-15.41.amzn1 (aws)
Mysql Server version : MySQL 5.6.35

### Docker informations
Docker compose version :
Docker version : 17.03.1-ce

### Problem's description

Hello,

When I run the image with the 3 volume definitions, It mounts it over the existing data.

example : 
without mounting  volumes (to persist data) : /usr/share/ocsinventory-reports/**ocsreports**
with mounting the volume (it mounts over the existing) : /usr/share/ocsinventory-reports/  is empty

A simple solution is to move data on other directory then copy back to volume (put that on the startup script)

regards,

**Comment by MyTheValentinus** [comment]
Hello,
This is specific to docker, you need to build image witth your volume, or copy back your files again.
I recommand you to work with stack file. You will be abble to intereact with volumes more easily and map after your volume by map specific volume to local directory where is stored ocsreports files.
Thanks
