### ISSUE TITLE
Failed opening required 'install.php' 

### ISSUE THREAD

**Issue by 90er** [OCSInventory-NG/OCSInventory-Docker-Image#32]
Docker host's operating system : CentOS 7.7.1908 (Core)
Mysql Server version : mysql:5.7.29

### Docker informations
Docker compose version : docker-compose version 1.25.0, build 0a186604
Docker version : Docker version 19.03.7, build 7141c199a2

### Problem's description
I will get the following error trying to start a blank instance of OCS Inventory (
https://raw.githubusercontent.com/OCSInventory-NG/OCSInventory-Docker-Image/master/2.6/docker-compose.yml):

Mon Mar 09 20:42:25.153375 2020] [php7:warn] [pid 175] [client 10.27.3.3:58771] PHP Warning:  

```
require(install.php): failed to open stream: No such file or directory in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 168
[Mon Mar 09 20:42:25.153399 2020] [php7:error] [pid 175] [client 10.27.3.3:58771] PHP Fatal error:  require(): Failed opening required 'install.php' (include_path='.:/opt/remi/php73/root/usr/share/pear:/opt/remi/php73/root/usr/share/php:/usr/share/pear:/usr/share/php') in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 168
```

### Fix
"wget https://raw.githubusercontent.com/OCSInventory-NG/OCSInventory-ocsreports/master/install.php" in "/usr/share/ocsinventory-reports/ocsreports/"

This error is posted quite often. I can't confirm that it's fixed with the Docker Image Release 2.6.

**Comment by gillesdubois** [comment]
Hi @90er, 

You shouldn't need the install.php file with compose file since the database is populated on docker start. Did you check the documentation here : http://wiki.ocsinventory-ng.org/13.Docker-documentation/Using-the-docker-image/

Also, are you sure you properly setup the env variables before running the image ?

Regards,
Gilles Dubois.

**Comment by celevra** [comment]
same error for me, fix helped, using standalone mariadb and docker without compose

**Comment by Edzilla2000** [comment]
I had the exact same issue today, so issue is still not fixed

**Comment by Edzilla2000** [comment]
I now understand what happened: the file ocsbase.sql must be in the sql subfolder, otherwise the SQL database is not set up.

**Comment by einsteinpei** [comment]
> Docker host's operating system : CentOS 7.7.1908 (Core)
> Mysql Server version : mysql:5.7.29
> 
> ### Docker informations
> Docker compose version : docker-compose version 1.25.0, build 0a186604
> Docker version : Docker version 19.03.7, build 7141c199a2
> 
> ### Problem's description
> I will get the following error trying to start a blank instance of OCS Inventory (
> https://raw.githubusercontent.com/OCSInventory-NG/OCSInventory-Docker-Image/master/2.6/docker-compose.yml):
> 
> Mon Mar 09 20:42:25.153375 2020] [php7:warn] [pid 175] [client 10.27.3.3:58771] PHP Warning:
> 
> ```
> require(install.php): failed to open stream: No such file or directory in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 168
> [Mon Mar 09 20:42:25.153399 2020] [php7:error] [pid 175] [client 10.27.3.3:58771] PHP Fatal error:  require(): Failed opening required 'install.php' (include_path='.:/opt/remi/php73/root/usr/share/pear:/opt/remi/php73/root/usr/share/php:/usr/share/pear:/usr/share/php') in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 168
> ```
> 
> ### Fix
> "wget https://raw.githubusercontent.com/OCSInventory-NG/OCSInventory-ocsreports/master/install.php" in "/usr/share/ocsinventory-reports/ocsreports/"
> 
> This error is posted quite often. I can't confirm that it's fixed with the Docker Image Release 2.6.

Thanks!

**Comment by sneakyx** [comment]
And don't forget to use MySQL 5.7. V8.0 doesn't work with standard settings. Maybe it works with mysql_native_password ? Didn't try it.
See also:  https://stackoverflow.com/a/49953657/8398149

**Comment by magenbrot** [comment]
> ### Fix
> "wget https://raw.githubusercontent.com/OCSInventory-NG/OCSInventory-ocsreports/master/install.php" in "/usr/share/ocsinventory-reports/ocsreports/"

I had the same problem. This workaround is still needed. Thx.

**Comment by damienvancouver** [comment]
This is still an issue in summer 2025, using the standalone docker image with my host machine's MariaDB.

if you don't use docker compose, then the standalone image is missing "install.php" and your database can't be populated.

I am using MariaDB and networking from my host, using --net=host , so I can connect to my local MariaDB.

I am starting with:  `docker run \
--net=host \
--name ocsinventory \
-e OCS_DB_NAME=ocsinventory \
-e OCS_DB_SERVER=localhost \
-e OCS_DB_PORT=3306 \
-e OCS_DB_USER=ocsinventory \
-e OCS_DB_PASS=uniquepassword1234 \
-itd \
ocsinventory/ocsinventory-docker-image:latest`

at which point the Ubuntu default page is visible at http://localhost , but http://localhost/ocsreports/ yields a 500 error and the error message from this thread.

I fixed it by connecting to the running "ocsinventory" docker container:  `docker exec -it ocsinventory bash`

which will open a shell inside the container.  Then download the missing file into the right place with:
```
# change to the correct directory inside the container
cd /usr/share/ocsinventory-reports/ocsreports/

# download the missing install.php file and set its ownership:
wget https://raw.githubusercontent.com/OCSInventory-NG/OCSInventory-ocsreports/master/install.php
chown www-data:www-data install.php

# double check it worked:
ls -l install.php     
# (it should look like:  -rw-r--r-- 1 www-data www-data 13023 Jul 11 02:19 install.php )

# If all good, exit the docker container:
exit
```

Now you should be able to hit http://localhost/ocsreports/ and finish off the install step.   The database information should already be filled in.  Hit "Next" and it will populate the database and finish things off.
You might need to also agree to a database update.. but eventually you should get to the login screen and be able to login with admin / admin
