### ISSUE TITLE
error launching docker compose 2.7

### ISSUE THREAD

**Issue by ortiga88** [OCSInventory-NG/OCSInventory-Docker-Image#35]
I attach the error that gives me:

```
docker-compose up -d
Pulling ocsapplication (ocsinventory/ocsinventory-docker-image:2.7)...
Trying to pull repository docker.io/ocsinventory/ocsinventory-docker-image ...
ERROR: manifest for docker.io/ocsinventory/ocsinventory-docker-image:2.7 not found
[root@localhost 2.7]# nano docker-compose.yml
Creating ocsinventory-db ... done
Creating ocsinventory-server ... error
Creating ocsinventory-server ...

ERROR: for ocsinventory-server  Cannot start service ocsapplication: oci runtime error: container_linux.go:235: starting container process caused "exec: \"/usr/bin/docker-entrypoint.sh\": permission denied"


ERROR: for ocsapplication  Cannot start service ocsapplication: oci runtime error: container_linux.go:235: starting container process caused "exec: \"/usr/bin/docker-entrypoint.sh\": permission denied"

ERROR: Encountered errors while bringing up the project.
```

**Comment by GaroneTux** [comment]
Same problem here, but on line 349...
ERROR: for ocsinventory-server  Cannot start service ocsapplication: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/usr/bin/docker-entrypoint.sh\": permission denied": unknown

ERROR: for ocsapplication  Cannot start service ocsapplication: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/usr/bin/docker-entrypoint.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project

**Comment by gillesdubois** [comment]
Hi,

2.7 tag wasn't pushed properly, could you try now please ?
Thanks.

Regards,
Gilles Dubois.

**Comment by karamfil** [comment]
Hi trying to run the latest version locally and ECS and get this

```
Error response from daemon: OCI runtime create failed: 
container_linux.go:349: starting container process caused 
"exec: \"/usr/bin/docker-entrypoint.sh\": permission denied": unknown```
