### ISSUE TITLE
Mismatch on APACHE_PID_FILE on Dockerfile

### ISSUE THREAD

**Issue by daurpam** [OCSInventory-NG/OCSInventory-Docker-Image#38]
### General informations
Docker host's operating system :  Debian 10.2
Mysql Server version :  5.7 (image inside docker-compose.yml)

### Docker informations
Docker compose version : 1.21.0, build unknown
Docker version : 19.03.6, build 369ce74a3c

### Problem's description on OCSInventory-Docker-Image version 2.7
When I try to use docker-compose.yml provided It is not possible to restart/start container completely, always show a message that apache still running because PID file exists. Searching to fix error, I guess there is a mistmatch on Dockerfile when ENV is declared. 

The APACHE_PID_FILE is named as **/var/run/httpd.pid** but is located in **/var/run/httpd/httpd.pid**

The only way to fix that is to use `docker-compose down` or include this variable as ENV on docker-compose.yml

Thanks for your work, hope you can fix it.

**Comment by Mad-Soft** [comment]
It's not the best way, but a workaround is in the file docker-entrypoint.sh
Before this line
`if [ -f "$APACHE_PID_FILE" ]; then`
put
`APACHE_PID_FILE=/var/run/httpd/httpd.pid`

Result:
`
........
# Apache start
if [ ! -d "$APACHE_RUN_DIR" ]; then
        mkdir "$APACHE_RUN_DIR"
        chown $APACHE_RUN_USER:$APACHE_RUN_GROUP "$APACHE_RUN_DIR"
fi
APACHE_PID_FILE=/var/run/httpd/httpd.pid
if [ -f "$APACHE_PID_FILE" ]; then
        rm "$APACHE_PID_FILE"
fi

/usr/sbin/httpd -DFOREGROUND
`

**Comment by gillesdubois** [comment]
Hi @Mad-Soft ,

I applied your fix on the master.
However if you see a cleaner way to proceed I'll gladly take it.

Regards,
Gilles Dubois.
