### ISSUE TITLE
missing LDAP options

### ISSUE THREAD

**Issue by slasse** [OCSInventory-NG/OCSInventory-Docker-Image#39]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Docker host's operating system : ubuntu 20.04
Mysql Server version : mysql 5.6

### Docker informations
Docker compose version : unrelated
Docker version : unrelated

### Problem's description
*Describe your problem here*
Missing the LDAP configuration options in the settings (configuration > general configuration).

when looking into the dockerfile i notice the php-ldap package is missing.

also i did not find a way to update the configuration in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/auth.php to set it up for ldap authentication as described in the documentation: https://wiki.ocsinventory-ng.org/04.Management-console-and-its-advanced-features/Synchronization-between-OCS-and-LDAP/

i tried to map the folder to my host machine and update the file that way but it gets overwritten when the container is started again.

is there a way to get ldap working with the docker image?

**Comment by gillesdubois** [comment]
Hi,

Docker image is by default in simplified configuration.
You need to activate "ADVANCE_CONFIGURATION" in the general config. (should be in interface tab)

Regards,
Gilles Dubois.

**Comment by slasse** [comment]
thanks, i ineed found that option.
i have one more question, in the documentation it is mentioned that you have to have a php ldap module and change something in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/auth.php and /usr/share/ocsinventory-reports/ocsreports/backend/identity/identity.php ($list_methode = array(0 => “local.php”); to $list_methode = array(0 => “ldap.php”);)

is that also needed in the docker container? i didn't really see a way to do this so i forked the repo and made some changes to the entrypoint file so it is working but doesn't seem ideal

**Comment by gillesdubois** [comment]
Hi @slasse 

Unfortunately we don't have a specific configuration for docker with LDAP and we don't plan to implement it for now.
On a bigger scale we are planning to rework the auth system so the file edit won't be necessary anymore.

**Comment by slasse** [comment]
ok good to know, thanks for the info
i was able to add it pretty simply in entrypoint.sh:

`if [[ $ldap = "true"  ]]; then
        sed -i 's/$list_methode = array(0 => "local.php");/$list_methode = array(0=>"ldap.php",1=>"local.php");/g' /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/auth.php
        sed -i 's/$list_methode = array(0 => "local.php");/$list_methode = array(0=>"ldap.php",1=>"local.php");/g' /usr/share/ocsinventory-reports/ocsreports/backend/identity/identity.php
fi` 

and adding the php73-php-ldap package to the yum packages.

you can then use an environment variable to activate or deactivate it
