### ISSUE TITLE
Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/usr/bin/docker-entrypoint.sh\": permission denied": unknown 	

### ISSUE THREAD

**Issue by AUGUSTOStephane** [OCSInventory-NG/OCSInventory-Docker-Image#40]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Docker host's operating system : GKE
Mysql Server version : 5.7

### Problem's description
Error: failed to start container  : 
Error  response from daemon: OCI runtime create failed:  container_linux.go:349: starting container process caused "exec:  \"/usr/bin/docker-entrypoint.sh\": permission denied": unknown |  
-- | --

**Comment by gillesdubois** [comment]
Hi,

I updated the permissions of the entry point and triggered a build on docker hub.
Please, can you test it again ?

Regards,
Gilles Dubois.

**Comment by AUGUSTOStephane** [comment]
it's ok.

**Comment by AUGUSTOStephane** [comment]
it's ok.
