### ISSUE TITLE
Issue to install OCS 2.6 with docker

### ISSUE THREAD

**Issue by aguilard07** [OCSInventory-NG/OCSInventory-Docker-Image#44]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Docker host's operating system : CentOS Linux release 7.8.2003 (Core)
Mysql Server version :  5.7

### Docker informations
Docker compose version : docker-compose version 1.26.2, build eefe0d31
Docker version : Docker version 19.03.12, build 48a66213fe

### Problem's description
After I execute the command `docker-compose up -d` to install OCS Inventory 2.6 with the docker image, I'm not able to change the mysql credentials. 

I made some configurations that I need, like use the 8005 and 8006 ports of the host to point the ports 80 and 443 of the ocsinventory-server, respectively.
When I try to access http://myip:8005/ocsreports, I got this error

![imagen](https://user-images.githubusercontent.com/51866788/90015714-f6051000-dc76-11ea-9170-73b7bd505c19.png)

this my docker-compose.yml
```
version: '3'

services:
  ocsapplication:
    image: ocsinventory/ocsinventory-docker-image:2.6
    container_name : ocsinventory-server
    restart: always
    ports:
      - 8005:80
      - 8006:443
    volumes:
      - "perlcomdata:/etc/ocsinventory-server"
      - "extensionsdata:/usr/share/ocsinventory-reports/ocsreports/extensions"
      - "varlibdata:/var/lib/ocsinventory-reports"
      - "httpdconfdata:/etc/httpd/conf.d"
    environment:
      OCS_DB_SERVER: ocsinventory-db
      OCS_DB_USER: operador
      OCS_DB_PASS: operador
      OCS_DB_NAME: ocsweb
    links:
      - ocsdb
    networks:
      - localocs
    depends_on:
      - ocsdb

  ocsdb :
    image : mysql:5.7
    container_name : ocsinventory-db
    restart: always
    ports :
      - 3306:3306
    volumes :
      - ./sql/:/docker-entrypoint-initdb.d/
      - sqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD : operador
      MYSQL_USER : operador
      MYSQL_PASSWORD : operador
      MYSQL_DATABASE : ocsweb
```

Maybe I'm not seeing something, can you help me please?

**Comment by gillesdubois** [comment]
Hi @aguilard07 ,

2.6 is not the latest version please try with the latest / 2.7 version.

Regards,
Gilles Dubois.
