### ISSUE TITLE
update docker image

### ISSUE THREAD

**Issue by DamienLGD** [OCSInventory-NG/OCSInventory-Docker-Image#46]
### General informations
Docker host's operating system : 
Mysql Server version : 

5.5.64-MariaDB MariaDB Server

### Problem's description

Hi,  
My database is on a mariadb server and i use ocsinventory (2.5) with docker    
I use this command to launch ocsinventory:  
docker run -p 80:80 --name myocsinventory --restart="always" -e OCS_DBNAME=db_ocs -e OCS_DBSERVER_READ=db.srv.int.xx.yy -e OCS_DBSERVER_WRITE=db.srv.int.xx.yy -e OCS_DBUSER=ocs -e OCS_DBPASS=password -itd ocsinventory/ocsinventory-docker-image:2.5  

It works very well but i try to replace this image with the 2.7 release (or 2.6) but i have this error on ocsinventory/ocsreports page:  
ERROR: MySql connection problem 2002
php_network_getaddresses: getaddrinfo failed: Name or service not known
ERROR: MySql connection problem 2002
php_network_getaddresses: getaddrinfo failed: Name or service not known

Is there a docker exec command to update the database schema (i think it is the problem) ?  

Thanks !

**Comment by gillesdubois** [comment]
Hi, 

Can you give me the command you use to run the 2.7 container ? 
2.5 and 2.7 image are really different so you might have to adapt your run command.

Regards,
Gilles Dubois.

**Comment by DamienLGD** [comment]
i do the same command but i change the .5 for a .7  

docker run -p 80:80 --name myocsinventory --restart="always" -e OCS_DBNAME=db_ocs -e OCS_DBSERVER_READ=db.srv.int.xx.yy -e OCS_DBSERVER_WRITE=db.srv.int.xx.yy -e OCS_DBUSER=ocs -e OCS_DBPASS=password -itd ocsinventory/ocsinventory-docker-image:2.7

**Comment by gillesdubois** [comment]
ENV var have changed : see https://github.com/OCSInventory-NG/OCSInventory-Docker-Image/blob/master/2.7/docker-compose.yml for some example with the 2.7 :) 

Also : http://wiki.ocsinventory-ng.org/13.Docker-documentation/Using-the-docker-image/

Regards,
Gilles Dubois.
