### ISSUE TITLE
Docker image for 2.4.1 is not available

### ISSUE THREAD

**Issue by indigo423** [OCSInventory-NG/OCSInventory-Docker-Image#5]
On docker hub only version 2.3.1 is available. Is this image actually not maintained anymore?

**Comment by MyTheValentinus** [comment]
Hello,
Thanks for your message, currently image for 2.4.1 is not fully tested, but i think the release come very soon.
Thanks

**Comment by N3RG4L** [comment]
Hi,

2.5 is out now, and docker image, not updated since 2.3.1
Is there someone who succeeded to create one and can share ?

Thanks

**Comment by MyTheValentinus** [comment]
Hello @N3RG4L,
Thanks for you interest for OCS Inventory, if you know how work docker images, you are welcome to contribute to the project !
I think a rework with newer version of debian base image would be benefit for future updates.
I come back soon to you with advancement state
Thanks

**Comment by MyTheValentinus** [comment]
Hello,
New version is available (2.5)
Thanks
