### ISSUE TITLE
docker-compose doesn't work

### ISSUE THREAD

**Issue by iloving** [OCSInventory-NG/OCSInventory-Docker-Image#52]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Docker host's operating system : Debian 10
Mysql Server version : 5.7.32

### Docker informations
Docker compose version : 1.21.0
Docker version : 1.5

### Problem's description
Docker containers using docker-compose doesn't work.
I tried 2.8.1 through 2.7 with the instructions provided in https://wiki.ocsinventory-ng.org/13.Docker-documentation/Using-the-docker-image/ but all they give me is the default centos apache page on port 80, and port 443 doesn't appear to be bound at all.  When I try 2.6, I get an empty index listing, as per the below screenshot
![image](https://user-images.githubusercontent.com/1250003/103938852-e213ec00-50f8-11eb-94c0-4c27b78306b7.png)

Either there is something wrong with these containers, or there are instructions missing.

**Comment by gillesdubois** [comment]
Hi,

There is no endpoint on / 

OCS Provide two endpoint : 
/ocsreports (the webconsole)
/ocsinventory (agent inventory endpoint)

Our image could implement a default redirect tho.

Regards,
Gilles.
