### ISSUE TITLE
"Bad Request" after clean deploy (tried multiple versions)

### ISSUE THREAD

**Issue by Elektordi** [OCSInventory-NG/OCSInventory-Docker-Image#53]
### General informations
Docker host's operating system : Ubuntu 18.04.5 LTS
Mysql Server version : tried 5.7 (from docker-compose) and 5.7.32 (on host)

### Docker informations
Docker compose version : 17.05.0-ce
Docker version : 1.10.0

### Problem's description
Tried to install OCS using docker-compose for a quick test, I got the following error on http://host_ip:8080/ocsinventory/

> Bad Request
> 
> Your browser sent a request that this server could not understand.

(I had to change the host port because port 80 is already used)

I tried 2.8.1 first, then 2.8 then 2.7, always the same error.
I then tried to remove everything, create local database on mysql server installed on host, and then deploy the image directly using docker run as stated in the documentation (without docker-compose) but I still have the same error.

I checked on container logs, and logs files inside container, I have nothing except the hit on the access_log:

`x.x.x.x - - [17/Feb/2021:20:00:18 +0100] "GET /ocsinventory/ HTTP/1.1" 400 226 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0"`

I tried to raise log level of httpd but nothing changes.

I also tried to make a voluntary mistake in conf, in this case I get a 500 error, and I have errors in the httpd error_log, but with the default conf, nothing at all... So it means perl code is running, but I have no clue on how to know what happends...

**Comment by dla-fritz** [comment]
I face the same error

**Comment by gillesdubois** [comment]
Hi,

The bad request is a normal behavior since you are accessing the /ocsinventory endpoint which is related to the agent.
If you want to reach the webconsole you have to use /ocsreports 

Regards,
Gilles.

**Comment by Elektordi** [comment]
Oh, ok... Thanks!

Maybe you should write that in the documentation (http://wiki.ocsinventory-ng.org/13.Docker-documentation/Using-the-docker-image/) and/or the docker hub page.

**Comment by gillesdubois** [comment]
I think there is a reference to that in the main section / Q&A of OCS. I'll check this in the next days on update the documentation :) 

Thanks for your input. 
Hope you will enjou OCS !
