### ISSUE TITLE
LDAP module missing 

### ISSUE THREAD

**Issue by fusmu** [OCSInventory-NG/OCSInventory-Docker-Image#54]
### General informations
Docker host's operating system : centos
Mysql Server version : 5.7

### Docker informations
Docker compose version :3
Docker version : 19.04

### Problem's description
php-ldap module missing and LDAP authentication is not usable, you could add another ENV that you can control authentication mechanism in var.php

**Comment by gillesdubois** [comment]
Hi,

Thanks for your report, we'll add this configuration for the 2.9 docker image.

Gilles.
