### ISSUE TITLE
ZipArchive php extension missing in ocsapplication image

### ISSUE THREAD

**Issue by nicorac** [OCSInventory-NG/OCSInventory-Docker-Image#56]
### General informations
Docker host's operating system : Ubuntu Server 20.04 x64
Mysql Server version : 5.7

### Docker informations
Docker compose version : 1.25.0
Docker version : 20.10.7
Image used: **latest**

### Problem's description
- Create a new deplyoment package
   Depolyment -> Build -> Windows -> Install/uninstall -> Execute an exe
- Set package name, description then add an .exe installer (I'm using Notepad++ 7.9.5 installer)
- Click on `Validate`

The build process starts but immediately stops with an WSOD-like page with only the purple `Reload build` button visible.

Apache log show this error:
`PHP Fatal error:  Uncaught Error: Class 'ZipArchive' not found in /usr/share/ocsinventory-reports/ocsreports/require/teledeploy/PackageBuilder.php:264\nStack trace:\n#0 /usr/share/ocsinventory-reports/ocsreports/require/teledeploy/PackageBuilder.php(122): PackageBuilder->zipScriptFile('/tmp/', 'phpOQx5oc', Object(SimpleXMLElement))\n#1 /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_teledeploy/ms_tele_build.php(50): PackageBuilder->buildPackage(Array, Array)\n#2 /usr/share/ocsinventory-reports/ocsreports/require/header.php(436): require('/usr/share/ocsi...')\n#3 /usr/share/ocsinventory-reports/ocsreports/index.php(44): require('/usr/share/ocsi...')\n#4 {main}\n  thrown in /usr/share/ocsinventory-reports/ocsreports/require/teledeploy/PackageBuilder.php on line 264, referer: http://xxxxxx/ocsreports/index.php?function=tele_build
`

**Comment by gillesdubois** [comment]
Hi,

I just added the dep in the 2.9 Docker file.

You will have to wait for our image to rebuild on docker hub to get the fix.

Regards,
Gilles.
