### ISSUE TITLE
Image with Tag 2.9 missing under DockerHub

### ISSUE THREAD

**Issue by eric-it6** [OCSInventory-NG/OCSInventory-Docker-Image#58]
Hello all,

we are eagerly awaiting version 2.9 of OCS, but currently can't deploy it.
i know that version 2.9 of OCS is already released but under DockerHub there is no tag for this version.

When I look under the latest image, I see a label with version 2.9. yes, I could use this image, but we don't want updates to be installed automatically.

Can you please create an extra image of version 2.9? This would help us a lot.

Many greetings
Eric

**Comment by gillesdubois** [comment]
Hey @eric-it6 

My bad, I forgot the most important step.
I'll push the 2.9 tag today.

Regards,
Gilles.

**Comment by eric-it6** [comment]
Big thank you for the quick feedback and implementation!
