### ISSUE TITLE
Add php73-php-ldap to OCS Inventory v2.8

### ISSUE THREAD

**Issue by balmha** [OCSInventory-NG/OCSInventory-Docker-Image#61]
### General informations
Docker host's operating system : Centos 7
OCS Version: 2.8

### Problem's description
I need add php73-php-ldap and php73-php-zip to Dockerfile in OCS Inventory Reports v2.8, you can help me?. I tried deploy OCS v2.9 but there are a few errors in my server that i cant resolve.

**Comment by Neustradamus** [comment]
Linked to this PR:
- https://github.com/OCSInventory-NG/OCSInventory-Docker-Image/pull/62

When it will be merged?

**Comment by gillesdubois** [comment]
Merged, test were done just forgot to merge it.

**Comment by Neustradamus** [comment]
@gillesdubois: Thanks!
