### ISSUE TITLE
How do I start  OCSInventory-Docker-Image?

### ISSUE THREAD

**Issue by jackadam1981** [OCSInventory-NG/OCSInventory-Docker-Image#9]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Docker host's operating system : fedora27
Mysql Server version : mariadb10.3.10

### Docker informations
Docker compose version :1.17.1
Docker version : 1.13.1

### Problem's description
*Describe your problem here*
Starting a OCSInventory container use docker-compose.yaml

version: "3"

services:
  ocs:
    image: ocsinventory/ocsinventory-docker-image
    container_name: ocs
    privileged: true
    ports:
    - "84:80"
    networks:
    - home
    environment:
      OCS_DBNAME: ocs
      OCS_DBSERVER_READ: ocs
      OCS_DBSERVER_WRITE: ocs
      OCS_DBUSER: ocs
      OCS_DBPASS: ocs
networks:
  home:

the network : home is network for MYSQL docker container 

can't use . just Apache2 Debian Default Page.

docker exec -it ocs bash   in the container  

i find OCSNG_UNIX_SERVER_2.5.tar.gz .
tar -xvf OCSNG_UNIX_SERVER_2.5.tar.gz.
cd OCSNG_UNIX_SERVER_2.5
chmod +x setup.sh  
./setup.sh 

*** Warning: PERL module Apache2::SOAP is not installed !
*** ERROR: PERL module Mojolicious::Lite is not installed !
*** ERROR: PERL module Switch is not installed !
*** ERROR: PERL module Plack::Handler is not installed !

perl -MCPAN -e shell   try install lost PERL moduld
install Apache2::SOAP
install Mojolicious::Lite
install  Switch
install Plack::Handler
perl -MCPAN -e "install Plack::Handler"

Test Summary Report
-------------------
t/HTTP-Message-PSGI/empty_streamed_response.t      (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/Plack-Middleware/access_log.t                    (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/Plack-Middleware/access_log_timed.t              (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/Plack-Middleware/access_log_value_zero.t         (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/Plack-Middleware/static_env.t                    (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/Plack-Middleware/urlmap_env.t                    (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=148, Tests=1174, 80 wallclock secs ( 1.65 usr  0.47 sys + 46.13 cusr  6.79 csys = 55.04 CPU)
Result: FAIL
Failed 6/148 test programs. 0/1174 subtests failed.
Makefile:1292: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255
  MIYAGAWA/Plack-1.0047.tar.gz
one dependency not OK (Apache::LogFormat::Compiler); additionally test harness failed
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports MIYAGAWA/Plack-1.0047.tar.gz

**Comment by chadyred** [comment]
Maybe take a look at here. This a stack I've done with `docker-compose` with GLPI and OCS : https://github.com/chadyred/glpi-ocsinventory-stack-docker

**Comment by jackadam1981** [comment]
Solution at https://github.com/OCSInventory-NG/OCSInventory-Docker-Image/issues/12#issue-389456864

Manual add "install.php" to “/ usr / share / ocsinventory-reports / ocsreports /”.
Or   remove line 100 
"rm /usr/share/ocsinventory-reports/ocsreports/install.php ;\"
from dockerfile, rebuild it.

**Comment by jackadam1981** [comment]
just miss install.php

**Comment by gillesdubois** [comment]
Hi,

Our Docker image has been reworked completly.
2.6 / nightly / dev tags are now available.

A complete documentation is available on our wiki.
Compose files are now located on the image repository and not on this one anymore.

Extension engine has been rework since it suffered from a bug in the earliers versions.

Regards,
Gilles Dubois.
