### ISSUE TITLE
nginx 404 not found for /ocsapi location 

### ISSUE THREAD

**Issue by albevt** [OCSInventory-NG/OCSInventory-Docker-Image#95]
I'm using 2.9.2 version in docker-compose
I was not able to get /ocsapi and nginx responde is 404 not found

I have found that the file
OCSInventory-Docker-Image/2.9.2/nginx/conf/ocsinventory.conf.template

is missing the directive proxy_pass for the location /ocsapi

I added following line at the end of location /ocsapi

proxy_pass http://ocsapplication/ocsap;

This solution work for me, and te ocsapi work properly.

**Comment by gillesdubois** [comment]
Hi @albevt 

The 2.11 image have been updated with the proxy pass instructions for nginx.

https://github.com/OCSInventory-NG/OCSInventory-Docker-Image/tree/master/2.11

Regards,
Gilles.
